# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: <pwned/>
email: guilherme@fireshellsecurity.team
description:
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://m4k4br0.github.io" # the base hostname & protocol for your site
twitter_username:
github_username:  m4k4br0

# Build settings
markdown: kramdown
